runs:
  run-1:
    condition: single_female
    positive_stream: single_female
    negative_stream: single_male
    audio_file: stimuli/single_female.wav
    acoustic_file: annotation/single_female_acoustic.csv
  run-2:
    condition: single_male
    positive_stream: single_male
    negative_stream: single_female
    audio_file: stimuli/single_male.wav
    acoustic_file: annotation/single_male_acoustic.csv
  run-3:
    condition: mix_attend_female
    positive_stream: single_female
    negative_stream: single_male
    audio_file: stimuli/mix.wav
    acoustic_file: annotation/mix_acoustic.csv
  run-4:
    condition: mix_attend_male
    positive_stream: single_male
    negative_stream: single_female
    audio_file: stimuli/mix.wav
    acoustic_file: annotation/mix_acoustic.csv
